variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

.build-arch-template: &build-template
  image: jonoh/docker-buildx-qemu
  stage: build
  script:
    - update-binfmts --enable
    - docker buildx create --driver docker-container --use

    - docker buildx build --platform linux/$CI_JOB_NAME
      -t genius -o type=docker,dest=- . > genius-img.tar
    - docker load < genius-$CI_JOB_NAME.tar
    - docker run --name c /bin/sh genius

    - docker cp c:/genius/target/release/genius .
    - docker rm -f c
  artifacts:
    paths:
      - genius-img.tar
      - genius

# this could be simplified
amd64:
  <<: *build-template

arm64:
  <<: *build-template
