variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

.build-arch-template: &build-template
  image: jonoh/docker-buildx-qemu
  before_script:
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap

    # https://askubuntu.com/a/1398147
    - docker pull tonistiigi/binfmt:latest
    - docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-*
    - docker run --privileged --rm tonistiigi/binfmt --install all

    - update-binfmts --enable

    - mkdir -p .cargo
    - echo -e "[net]\ngit-fetch-with-cli = true" > .cargo/config

  script:
    - ls -a
    - docker buildx build --platform linux/$CI_JOB_NAME
      -t genius -o type=docker,dest=- . > genius-img.tar
    - docker load < genius-img.tar
    - docker run --name genius genius /bin/sh

    - docker cp genius:/genius/target .
    - docker cp genius:/usr/local/cargo .
    - ls
    - docker rm -f genius

  artifacts:
    paths:
      - genius-img.tar
      - target/release/genius

  cache:
    untracked: true
    key: $CI_JOB_NAME
    paths:
      - cargo
      - target
    when: always

# this could be simplified
amd64:
  stage: build
  <<: *build-template

arm64:
  stage: build
  <<: *build-template
