image: debian

before_script:
  - apt-get update -y
  - apt-get install -y
      docker.io
      binfmt-support
      qemu-user-static
      curl
  - update-binfmts --enable

  # install
  - docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-*
  - docker run --privileged --rm tonistiigi/binfmt --install all

  # install-buildx-plugin
  - mkdir -p ~/.docker/cli-plugins
  - curl -s https://api.github.com/repos/docker/buildx/releases/latest |
      grep "browser_download_url.*linux-amd64" | cut -d ':' -f 2,3 | tr -d \" |
      xargs curl -L -o ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

  # use docker-container buildx plugin
  - docker buildx create --driver docker-container --use
  - docker buildx inspect --bootstrap

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

.build-arch-template: &build-template
  stage: build
  script:
    - docker buildx build --platform linux/$CI_JOB_NAME -t genius .
    - docker export --output="genius-$CI_JOB_NAME.tar" genius
  artifacts:
    paths:
      - genius-$CI_JOB_NAME.tar

amd64:
  <<: *build-template

arm64:
  <<: *build-template
