image: "debian:latest"

# install rust and libssl dependency
before_script:
  - dpkg --add-architecture arm64
  - apt-get update -y
  - apt-get install -y qemu-user wget git automake:arm64 pkg-config:arm64 gcc:arm64 \
    libssl-dev:arm64 jq:arm64
  - wget https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-gnu/rustup-init
  - chmod +x rustup-init
  - ./rustup-init -y --profile minimal
  - source "$HOME/.cargo/env"

cache:
  key:
  paths:
    - target/
    - ~/.cargo/registry

build:
  script:
    - cargo build --release

  artifacts:
    paths:
      - target/release/genius
