image: debian

before_script:
  - apt-get update -y
  - apt-get install -y
      docker.io
      binfmt-support
      qemu-user-static
  - update-binfmts --enable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

.build-arch-template: &build-template
  stage: build
  script:
    - docker build --platform linux/$CI_JOB_NAME -t genius .
    - docker export --output="genius-$CI_JOB_NAME.tar" genius
  artifacts:
    paths:
      - genius-$CI_JOB_NAME.tar

build:x86:
  <<: *build-template

build:arm64:
  <<: *build-template
