image: debian

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

.build-arch-template: &build-template
  image: jonoh/docker-buildx-qemu
  stage: build
  script:
    - update-binfmts --enable
    - docker buildx create --driver docker-container --use
    - docker buildx build --platform linux/$CI_JOB_NAME
      -o type=docker,dest=- . > genius-$CI_JOB_NAME.tar
  artifacts:
    paths:
      - genius-$CI_JOB_NAME.tar

amd64:
  <<: *build-template

arm64:
  <<: *build-template
