image: jonoh/docker-buildx-qemu

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - build

x86:
  stage: build
  before_script:
    - update-binfmts --enable
  script:
    - docker buildx build --platform linux/amd64 -t genius .
    - docker export --output="genius.tar" genius
  artifacts:
    paths:
      - genius.tar

arm64:
  stage: build
  before_script:
    - update-binfmts --enable
  script:
    - docker buildx build --platform linux/arm64 -t genius .
    - docker export --output="genius.tar" genius
  artifacts:
    paths:
      - genius.tar
