[package]
name = "genius"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = "2"
rand = "0.8.0"
reqwest = { version = "0.11" }
scraper = "0.12.0"
jq-rs = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
# tracing = "0.1.23"
# tracing-subscriber = "0.2"
regex = "1.5.4"
dotenv = "0.15.0"

[dependencies.serenity]
version = "0.10"
features = ["collector"]
