FROM rust:alpine

WORKDIR /usr/src/genius-bot
COPY . .

RUN apk update
RUN apk add openssl jq imagemagick font-noto font-noto-emoji
# ENV OPENSSL_DIR=/etc/ssl
# RUN rustup target add armv7-unknown-linux-gnueabihf

RUN cargo build --target=armv7-unknown-linux-gnueabihf --release

CMD cargo run --release
