name: Build docker image and push to ECR

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: Target AWS Region
        type: string
      aws_account_id:
        description: AWS Account ID
        type: string
      aws_ecr_repo_url:
        description: AWS ECR Repository URL
        type: string

permissions:
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      my-registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws_role }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/aws-actions/amazon-ecr-login
      - name: Build, tag and push the image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.aws_ecr_repo_url }}
          IMAGE_TAG: latest
        run: |
          docker buildx build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
